In [2]:
typeof(1+3+5.)

Float64

In [ ]:
println("αβγ⋄♢∑€£€")

In [28]:
abstypevariable = Array{Integer,2}(undef, 2,3)


2×3 Array{Integer,2}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [29]:
typeof(abstypevariable)

Array{Integer,2}

In [9]:
abstypevariable

UndefRefError: UndefRefError: access to undefined reference

In [13]:
abstypevariable[2,2] = 7.0

7.0

In [14]:
abstypevariable

2×3 Array{Integer,2}:
 #undef  #undef  #undef
 #undef    7     #undef

In [15]:
arbconcretevariable = Array{Int64}(undef, 2,3)

2×3 Array{Int64,2}:
 1  1  1
 1  0  0

In [1]:
? floor #question mark gives help

search: floor OverflowError StackOverflowError



```
floor([T,] x)
floor(x; digits::Integer= [, base = 10])
floor(x; sigdigits::Integer= [, base = 10])
```

`floor(x)` returns the nearest integral value of the same type as `x` that is less than or equal to `x`.

`floor(T, x)` converts the result to type `T`, throwing an `InexactError` if the value is not representable.

`digits`, `sigdigits` and `base` work as for [`round`](@ref).

---

```
floor(x::Period, precision::T) where T <: Union{TimePeriod, Week, Day} -> T
```

Round `x` down to the nearest multiple of `precision`. If `x` and `precision` are different subtypes of `Period`, the return value will have the same type as `precision`.

For convenience, `precision` may be a type instead of a value: `floor(x, Dates.Hour)` is a shortcut for `floor(x, Dates.Hour(1))`.

```jldoctest
julia> floor(Dates.Day(16), Dates.Week)
2 weeks

julia> floor(Dates.Minute(44), Dates.Minute(15))
30 minutes

julia> floor(Dates.Hour(36), Dates.Day)
1 day
```

Rounding to a `precision` of `Month`s or `Year`s is not supported, as these `Period`s are of inconsistent length.

---

```
floor(dt::TimeType, p::Period) -> TimeType
```

Return the nearest `Date` or `DateTime` less than or equal to `dt` at resolution `p`.

For convenience, `p` may be a type instead of a value: `floor(dt, Dates.Hour)` is a shortcut for `floor(dt, Dates.Hour(1))`.

```jldoctest
julia> floor(Date(1985, 8, 16), Dates.Month)
1985-08-01

julia> floor(DateTime(2013, 2, 13, 0, 31, 20), Dates.Minute(15))
2013-02-13T00:30:00

julia> floor(DateTime(2016, 8, 6, 12, 0, 0), Dates.Day)
2016-08-06T00:00:00
```


In [6]:
# type letter and press tab to see all the functions (currently available)


LoadError: syntax: invalid identifier name "?"

In [8]:
? muladd

search: muladd



```
muladd(x, y, z)
```

Combined multiply-add: computes `x*y+z`, but allowing the add and multiply to be merged with each other or with surrounding operations for performance. For example, this may be implemented as an [`fma`](@ref) if the hardware supports it efficiently. The result can be different on different machines and can also be different on the same machine due to constant propagation or other optimizations. See [`fma`](@ref).

# Examples

```jldoctest
julia> muladd(3, 2, 1)
7

julia> 3 * 2 + 1
7
```


### Functions

In [10]:
myfunc(firstvar) = 20*firstvar
myfunc(333.231)

6664.62

In [13]:
function myfunc2(var1)
    println(var1*2)
    println("function finished")
end

x = myfunc2(20)

40
function finished


In [15]:
30 \ 20


0.6666666666666666

In [16]:
funcy(x) = return x
funcy(8)

8